[tool.poetry]
name = "ti"
version = "0.1.0"
description = "Not a silly simple time tracker"
authors = ["Gilad Barnea <giladbrn@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
dateparser = "^1.0.0"
rich = {version = "^10.1.0", optional = true}

[tool.poetry.dev-dependencies]
cram = "^0.7"
pytest-cram = "^0.2.2"
ipython = "^7.22.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
